In [72]:
import pandas as pd
import numpy as np

In [73]:
df = pd.read_csv('ModeChoiceOptima.txt',sep='\t')

In [74]:
df.head()

,ID,DestAct,NbTransf,TimePT,WalkingTimePT,WaitingTimePT,CostPT,CostCar,TimeCar,NbHousehold,...,FreqTripHouseh,Region,distance_km,Choice,InVehicleTime,ModeToSchool,ReportedDuration,CoderegionCAR,age,Weight
0,10350017,2,4,85,23,10,12.4,3.17,32,2,...,4,1,30.0,1,52,3,255,1,27,0.000379
1,10350020,1,4,108,26,16,12.4,3.28,30,2,...,4,1,32.0,-1,66,3,150,1,28,0.000341
2,10350025,11,2,82,33,5,3.0,0.45,6,-1,...,2,1,4.5,0,44,-1,20,1,-1,0.000368
3,10350075,1,3,107,21,31,24.0,2.36,23,2,...,1,1,25.0,1,55,-1,30,1,63,0.000368
4,10350085,1,5,190,116,18,10.8,1.16,14,3,...,3,1,12.5,1,56,-1,20,1,57,0.000409

In [75]:
df.shape

(2265, 117)

In [76]:
df.columns

Index(['ID', 'DestAct', 'NbTransf', 'TimePT', 'WalkingTimePT', 'WaitingTimePT',
       'CostPT', 'CostCar', 'TimeCar', 'NbHousehold',
       ...
       'FreqTripHouseh', 'Region', 'distance_km', 'Choice', 'InVehicleTime',
       'ModeToSchool', 'ReportedDuration', 'CoderegionCAR', 'age', 'Weight'],
      dtype='str', length=117)

In [77]:
df.count()

ID                  2265
DestAct             2265
NbTransf            2265
TimePT              2265
WalkingTimePT       2265
                    ...
ModeToSchool        2265
ReportedDuration    2265
CoderegionCAR       2265
age                 2265
Weight              2265
Length: 117, dtype: int64

In [78]:
df.describe()

,ID,DestAct,NbTransf,TimePT,WalkingTimePT,WaitingTimePT,CostPT,CostCar,TimeCar,NbHousehold,...,FreqTripHouseh,Region,distance_km,Choice,InVehicleTime,ModeToSchool,ReportedDuration,CoderegionCAR,age,Weight
count,2.265000e+03,2265.000000,2265.000000,2265.000000,2265.000000,2265.000000,2265.000000,2265.000000,2265.000000,2265.000000,...,2265.000000,2265.000000,2265.000000,2265.000000,2265.000000,2265.000000,2265.000000,2265.000000,2265.000000,2265.000000
mean,4.506873e+07,4.139073,2.132450,113.619868,40.842384,13.739956,20.483642,4.467982,44.452539,2.589845,...,2.689625,4.483885,45.179695,0.496689,59.161148,3.726711,62.952759,4.483885,46.598234,0.000442
std,2.402392e+07,3.559886,2.244178,91.172432,28.824180,21.968595,26.050610,6.636505,53.662723,1.501172,...,1.324678,2.103512,71.825115,0.817278,61.708473,1.771864,78.872330,2.103512,18.974625,0.000550
min,1.035002e+07,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,...,-2.000000,1.000000,0.000000,-1.000000,-1.000000,-2.000000,-1.000000,1.000000,-1.000000,0.000077
25%,2.824097e+07,1.000000,0.000000,50.000000,20.000000,0.000000,6.000000,1.080000,14.000000,2.000000,...,2.000000,3.000000,9.500000,0.000000,18.000000,3.000000,18.000000,3.000000,38.000000,0.000126
50%,4.464044e+07,3.000000,2.000000,91.000000,34.000000,6.000000,11.000000,2.240000,28.000000,2.000000,...,3.000000,5.000000,20.000000,1.000000,43.000000,4.000000,39.000000,5.000000,47.000000,0.000321
75%,5.444027e+07,7.000000,4.000000,149.000000,53.000000,19.000000,24.200000,4.900000,54.000000,4.000000,...,4.000000,6.000000,49.000000,1.000000,78.000000,5.000000,77.000000,6.000000,60.000000,0.000409
max,9.604054e+07,11.000000,15.000000,826.000000,306.000000,392.000000,230.000000,57.170000,494.000000,10.000000,...,4.000000,8.000000,642.000000,2.000000,631.000000,8.000000,855.000000,8.000000,88.000000,0.007572

In [79]:
#Cleaning up of data, removing rows with age -1 
df_mod=df.copy()

In [80]:
#Original data frame count
df_mod.count()

ID                  2265
DestAct             2265
NbTransf            2265
TimePT              2265
WalkingTimePT       2265
                    ...
ModeToSchool        2265
ReportedDuration    2265
CoderegionCAR       2265
age                 2265
Weight              2265
Length: 117, dtype: int64

In [81]:
#Cleaning the Environmental Attitudes
#Envir01
df_mod[df_mod['Envir01']==-2]
df_mod.drop(df_mod[df_mod['Envir01']==-2].index,inplace=True)
df_mod[df_mod['Envir01']==-2]

df_mod[df_mod['Envir01']==-1]
df_mod.drop(df_mod[df_mod['Envir01']==-1].index,inplace=True)
df_mod[df_mod['Envir01']==-1]

#Cleaning the Environmental Attitudes
#Envir02
df_mod[df_mod['Envir02']==-1]
df_mod.drop(df_mod[df_mod['Envir02']==-1].index,inplace=True)
df_mod[df_mod['Envir02']==-1]

#Cleaning the Environmental Attitudes
#Envir03
df_mod[df_mod['Envir03']==-1]
df_mod.drop(df_mod[df_mod['Envir03']==-1].index,inplace=True)
df_mod[df_mod['Envir03']==-1]

#Envir04
df_mod[df_mod['Envir04']<0]
df_mod.drop(df_mod[df_mod['Envir04']<0].index,inplace=True)
df_mod[df_mod['Envir04']<0]

#Envir05
df_mod[df_mod['Envir05']<0]
df_mod.drop(df_mod[df_mod['Envir05']<0].index,inplace=True)
df_mod[df_mod['Envir05']<0]

#Envir06
df_mod[df_mod['Envir06']<0]
df_mod.drop(df_mod[df_mod['Envir06']<0].index,inplace=True)
df_mod[df_mod['Envir06']<0]

Empty DataFrame
Columns: [ID, DestAct, NbTransf, TimePT, WalkingTimePT, WaitingTimePT, CostPT, CostCar, TimeCar, NbHousehold, NbChild, NbCar, NbMoto, NbBicy, NbBicyChild, NbComp, NbTV, Internet, NewsPaperSubs, NbCellPhones, NbSmartPhone, HouseType, OwnHouse, NbRoomsHouse, YearsInHouse, Income, Gender, BirthYear, Mothertongue, FamilSitu, OccupStat, SocioProfCat, CalculatedIncome, Education, HalfFareST, LineRelST, GenAbST, AreaRelST, OtherST, CarAvail, MarginalCostPT, CostCarCHF, Envir01, Envir02, Envir03, Envir04, Envir05, Envir06, Mobil01, Mobil02, Mobil03, Mobil04, Mobil05, Mobil06, Mobil07, Mobil08, Mobil09, Mobil10, Mobil11, Mobil12, Mobil13, Mobil14, Mobil15, Mobil16, Mobil17, Mobil18, Mobil19, Mobil20, Mobil21, Mobil22, Mobil23, Mobil24, Mobil25, Mobil26, Mobil27, ResidCh01, ResidCh02, ResidCh03, ResidCh04, ResidCh05, ResidCh06, ResidCh07, LifSty01, LifSty02, LifSty03, LifSty04, LifSty05, LifSty06, LifSty07, LifSty08, LifSty09, LifSty10, LifSty11, LifSty12, LifSty13, LifSty14, TripPurpose, TypeCommune, UrbRur, LangCode, ...]
Index: []

[0 rows x 117 columns]

In [82]:
#Count of the cleaned data frame from Environmental Attitudes
df_mod.count()
df_env=df_mod.copy()

In [83]:
#Drop rows with Choice -1 and check the description of Choice column again
df_mod.drop(df_mod[df_mod['Choice']==-1].index,inplace=True)
df_mod[df_mod['Choice']==-1]

#Drop rows with InVehicleTime -1 and check the description of InVehicleTime column again
df_mod[df_mod['InVehicleTime']==-1]
df_mod.drop(df_mod[df_mod['InVehicleTime']==-1].index,inplace=True)
df_mod[df_mod['InVehicleTime']==-1]

#Drop rows with age -1 and check the description of age column again
df_mod.drop(df_mod[df_mod['age']==-1].index,inplace=True)
df_mod[df_mod['age']==-1]

#Drop rows with InVehicleTime -1 and check the description of InVehicleTime column again
df_mod[df_mod['InVehicleTime']==-1]
df_mod.drop(df_mod[df_mod['InVehicleTime']==-1].index,inplace=True)
df_mod[df_mod['InVehicleTime']==-1]

#Drop rows with ReportedDuration -1 and check the description of ReportedDuration column again
df_mod[df_mod['ReportedDuration']==-1]
df_mod.drop(df_mod[df_mod['ReportedDuration']==-1].index,inplace=True)
df_mod[df_mod['ReportedDuration']==-1]

#Drop rows with NbCar -1 and check the description of NbCar column again
df_mod[df_mod['NbCar']==-1]
df_mod.drop(df_mod[df_mod['NbCar']==-1].index,inplace=True)
df_mod[df_mod['NbCar']==-1]

#Drop rows with NbBicy -1 and check the description of NbBicy column again
df_mod[df_mod['NbBicy']<0]
df_mod.drop(df_mod[df_mod['NbBicy']<0].index,inplace=True)
df_mod[df_mod['NbBicy']<0]

#Drop rows with NbMoto -1 and check the description of NbMoto column again
df_mod[df_mod['NbMoto']<0]
df_mod.drop(df_mod[df_mod['NbMoto']<0].index,inplace=True) 
df_mod[df_mod['NbMoto']<0]

#Drop rows with NbChild -1 and check the description of NbChild column again
df_mod[df_mod['NbChild']<0]
df_mod.drop(df_mod[df_mod['NbChild']<0].index,inplace=True)

#Drop rows with NbHousehold -1 and check the description of NbHousehold column again
df_mod[df_mod['NbHousehold']<0]
df_mod.drop(df_mod[df_mod['NbHousehold']<0].index,inplace=True)
df_mod[df_mod['NbHousehold']<0]

#Drop rows with NbComp -1 and check the description of NbComp column again
df_mod[df_mod['NbComp']<0]
df_mod.drop(df_mod[df_mod['NbComp']<0].index,inplace=True)
df_mod[df_mod['NbComp']<0]

#Drop rows with NbTV -1 and check the description of NbTV column again
df_mod[df_mod['NbTV']<0]
df_mod.drop(df_mod[df_mod['NbTV']<0].index,inplace=True)
df_mod[df_mod['NbTV']<0]

Empty DataFrame
Columns: [ID, DestAct, NbTransf, TimePT, WalkingTimePT, WaitingTimePT, CostPT, CostCar, TimeCar, NbHousehold, NbChild, NbCar, NbMoto, NbBicy, NbBicyChild, NbComp, NbTV, Internet, NewsPaperSubs, NbCellPhones, NbSmartPhone, HouseType, OwnHouse, NbRoomsHouse, YearsInHouse, Income, Gender, BirthYear, Mothertongue, FamilSitu, OccupStat, SocioProfCat, CalculatedIncome, Education, HalfFareST, LineRelST, GenAbST, AreaRelST, OtherST, CarAvail, MarginalCostPT, CostCarCHF, Envir01, Envir02, Envir03, Envir04, Envir05, Envir06, Mobil01, Mobil02, Mobil03, Mobil04, Mobil05, Mobil06, Mobil07, Mobil08, Mobil09, Mobil10, Mobil11, Mobil12, Mobil13, Mobil14, Mobil15, Mobil16, Mobil17, Mobil18, Mobil19, Mobil20, Mobil21, Mobil22, Mobil23, Mobil24, Mobil25, Mobil26, Mobil27, ResidCh01, ResidCh02, ResidCh03, ResidCh04, ResidCh05, ResidCh06, ResidCh07, LifSty01, LifSty02, LifSty03, LifSty04, LifSty05, LifSty06, LifSty07, LifSty08, LifSty09, LifSty10, LifSty11, LifSty12, LifSty13, LifSty14, TripPurpose, TypeCommune, UrbRur, LangCode, ...]
Index: []

[0 rows x 117 columns]

In [ ]:
df_mod.count()

In [84]:
#Drop rows with CarAvail -1 and check the description of CarAvail column again
df_mod[df_mod['CarAvail']==-1]
df_mod.drop(df_mod[df_mod['CarAvail']==-1].index,inplace=True)
df_mod[df_mod['CarAvail']==-1]

#Count of the cleaned data frame from CarAvail Attitudes
df_mod.count()

ID                  1471
DestAct             1471
NbTransf            1471
TimePT              1471
WalkingTimePT       1471
                    ...
ModeToSchool        1471
ReportedDuration    1471
CoderegionCAR       1471
age                 1471
Weight              1471
Length: 117, dtype: int64

In [85]:
#Drop rows with Choice -1 and check the description of Choice column again
df_mod.drop(df_mod[df_mod['Choice']==-1].index,inplace=True)
df_mod[df_mod['Choice']==-1]

#Checking the count of the cleaned data frame
df_mod.count()

ID                  1471
DestAct             1471
NbTransf            1471
TimePT              1471
WalkingTimePT       1471
                    ...
ModeToSchool        1471
ReportedDuration    1471
CoderegionCAR       1471
age                 1471
Weight              1471
Length: 117, dtype: int64

In [86]:
#cleaning the mobility tool ownership variables
#Mobility Attitudes
df_mod[df_mod['Mobil01']==-1]
df_mod.drop(df_mod[df_mod['Mobil01']==-1].index,inplace=True)

df_mod[df_mod['Mobil02']==-1]
df_mod.drop(df_mod[df_mod['Mobil02']==-1].index,inplace=True)

df_mod[df_mod['Mobil03']==-1]
df_mod.drop(df_mod[df_mod['Mobil03']==-1].index,inplace=True)

df_mod[df_mod['Mobil04']==-1]
df_mod.drop(df_mod[df_mod['Mobil04']==-1].index,inplace=True)

df_mod[df_mod['Mobil05']==-1]
df_mod.drop(df_mod[df_mod['Mobil05']==-1].index,inplace=True)

df_mod[df_mod['Mobil06']==-1]
df_mod.drop(df_mod[df_mod['Mobil06']==-1].index,inplace=True)

df_mod[df_mod['Mobil07']==-1]
df_mod.drop(df_mod[df_mod['Mobil07']==-1].index,inplace=True)

df_mod[df_mod['Mobil08']==-1]
df_mod.drop(df_mod[df_mod['Mobil08']==-1].index,inplace=True)

df_mod[df_mod['Mobil09']==-1] 
df_mod.drop(df_mod[df_mod['Mobil09']==-1].index,inplace=True)

df_mod[df_mod['Mobil10']==-1]
df_mod.drop(df_mod[df_mod['Mobil10']==-1].index,inplace=True)

df_mod[df_mod['Mobil11']==-1]
df_mod.drop(df_mod[df_mod['Mobil11']==-1].index,inplace=True)

df_mod[df_mod['Mobil12']==-1]
df_mod.drop(df_mod[df_mod['Mobil12']==-1].index,inplace=True)

df_mod[df_mod['Mobil13']==-1]
df_mod.drop(df_mod[df_mod['Mobil13']==-1].index,inplace=True)

df_mod[df_mod['Mobil14']==-1]
df_mod.drop(df_mod[df_mod['Mobil14']==-1].index,inplace=True)

df_mod[df_mod['Mobil15']==-1]
df_mod.drop(df_mod[df_mod['Mobil15']==-1].index,inplace=True)

df_mod[df_mod['Mobil16']==-1]
df_mod.drop(df_mod[df_mod['Mobil16']==-1].index,inplace=True)

df_mod[df_mod['Mobil17']==-1]
df_mod.drop(df_mod[df_mod['Mobil17']==-1].index,inplace=True)

df_mod[df_mod['Mobil18']==-1]
df_mod.drop(df_mod[df_mod['Mobil18']==-1].index,inplace=True)

df_mod[df_mod['Mobil19']==-1]
df_mod.drop(df_mod[df_mod['Mobil19']==-1].index,inplace=True)

df_mod[df_mod['Mobil20']==-1]
df_mod.drop(df_mod[df_mod['Mobil20']==-1].index,inplace=True)

df_mod[df_mod['Mobil21']==-1]
df_mod.drop(df_mod[df_mod['Mobil21']==-1].index,inplace=True)

df_mod[df_mod['Mobil22']==-1]
df_mod.drop(df_mod[df_mod['Mobil22']==-1].index,inplace=True)

df_mod[df_mod['Mobil23']==-1]
df_mod.drop(df_mod[df_mod['Mobil23']==-1].index,inplace=True)

df_mod[df_mod['Mobil24']==-1]
df_mod.drop(df_mod[df_mod['Mobil24']==-1].index,inplace=True)

df_mod[df_mod['Mobil25']==-1]
df_mod.drop(df_mod[df_mod['Mobil25']==-1].index,inplace=True)

df_mod[df_mod['Mobil26']==-1]
df_mod.drop(df_mod[df_mod['Mobil26']==-1].index,inplace=True)

df_mod[df_mod['Mobil27']==-1]
df_mod.drop(df_mod[df_mod['Mobil27']==-1].index,inplace=True)

In [87]:
df_mod.count()

ID                  1391
DestAct             1391
NbTransf            1391
TimePT              1391
WalkingTimePT       1391
                    ...
ModeToSchool        1391
ReportedDuration    1391
CoderegionCAR       1391
age                 1391
Weight              1391
Length: 117, dtype: int64

In [88]:
#Main Variables of interest
df_mod[df_mod['TripPurpose']==-1]
df_mod.drop(df_mod[df_mod['TripPurpose']==-1].index,inplace=True)
df_mod[df_mod['TripPurpose']==-1]

df_mod[df_mod['DestAct']==-1]
df_mod.drop(df_mod[df_mod['DestAct']==-1].index,inplace=True)
df_mod[df_mod['DestAct']==-1]

df_mod[df_mod['FreqTripHouseh']<0]
df_mod.drop(df_mod[df_mod['FreqTripHouseh']<0].index,inplace=True)
df_mod[df_mod['FreqTripHouseh']<0]

Empty DataFrame
Columns: [ID, DestAct, NbTransf, TimePT, WalkingTimePT, WaitingTimePT, CostPT, CostCar, TimeCar, NbHousehold, NbChild, NbCar, NbMoto, NbBicy, NbBicyChild, NbComp, NbTV, Internet, NewsPaperSubs, NbCellPhones, NbSmartPhone, HouseType, OwnHouse, NbRoomsHouse, YearsInHouse, Income, Gender, BirthYear, Mothertongue, FamilSitu, OccupStat, SocioProfCat, CalculatedIncome, Education, HalfFareST, LineRelST, GenAbST, AreaRelST, OtherST, CarAvail, MarginalCostPT, CostCarCHF, Envir01, Envir02, Envir03, Envir04, Envir05, Envir06, Mobil01, Mobil02, Mobil03, Mobil04, Mobil05, Mobil06, Mobil07, Mobil08, Mobil09, Mobil10, Mobil11, Mobil12, Mobil13, Mobil14, Mobil15, Mobil16, Mobil17, Mobil18, Mobil19, Mobil20, Mobil21, Mobil22, Mobil23, Mobil24, Mobil25, Mobil26, Mobil27, ResidCh01, ResidCh02, ResidCh03, ResidCh04, ResidCh05, ResidCh06, ResidCh07, LifSty01, LifSty02, LifSty03, LifSty04, LifSty05, LifSty06, LifSty07, LifSty08, LifSty09, LifSty10, LifSty11, LifSty12, LifSty13, LifSty14, TripPurpose, TypeCommune, UrbRur, LangCode, ...]
Index: []

[0 rows x 117 columns]

In [111]:
#Cleaning the ModeToSchool variable
df_mod[df_mod['ModeToSchool']==-1]
df_mod.drop(df_mod[df_mod['ModeToSchool']==-1].index,inplace=True)
df_mod[df_mod['ModeToSchool']==-1]

#Cleaning FReqTripHouseh variable
df_mod[df_mod['FreqTripHouseh']==-1]

#Cleaning ResidChild variable
df_mod[df_mod['ResidChild']<0]  
df_mod.drop(df_mod[df_mod['ResidChild']<0].index,inplace=True)
df_mod[df_mod['ResidChild']<0]

#Cleaning FreqCarPar variable
df_mod[df_mod['FreqCarPar']<0]
df_mod.drop(df_mod[df_mod['FreqCarPar']<0].index,inplace=True)
df_mod[df_mod['FreqCarPar']<0]

#Cleaning FreqTrainPar variable
df_mod[df_mod['FreqTrainPar']<0]
df_mod.drop(df_mod[df_mod['FreqTrainPar']<0].index,inplace=True)
df_mod[df_mod['FreqTrainPar']<0]

#Cleaning FreqOthPar variable
df_mod[df_mod['FreqOtherPar']<0]
df_mod.drop(df_mod[df_mod['FreqOtherPar']<0].index,inplace=True)
df_mod[df_mod['FreqOtherPar']<0]

#Cleaning Internet variable
df_mod[df_mod['Internet']<0]
df_mod.drop(df_mod[df_mod['Internet']<0].index,inplace=True)
df_mod[df_mod['Internet']<0]

#Cleaning NewspaperSubs variable
df_mod[df_mod['NewsPaperSubs']<0]
df_mod.drop(df_mod[df_mod['NewsPaperSubs']<0].index,inplace=True)
df_mod[df_mod['NewsPaperSubs']<0]

#Cleaning NbCellPhones
df_mod[df_mod['NbCellPhones']<0]
df_mod.drop(df_mod[df_mod['NbCellPhones']<0].index,inplace=True)
df_mod[df_mod['NbCellPhones']<0]

#Cleaning NbSmartPhones
df_mod[df_mod['NbSmartPhone']<0]
df_mod.drop(df_mod[df_mod['NbSmartPhone']<0].index,inplace=True)
df_mod[df_mod['NbSmartPhone']<0]

Empty DataFrame
Columns: [ID, DestAct, NbTransf, TimePT, WalkingTimePT, WaitingTimePT, CostPT, CostCar, TimeCar, NbHousehold, NbChild, NbCar, NbMoto, NbBicy, NbBicyChild, NbComp, NbTV, Internet, NewsPaperSubs, NbCellPhones, NbSmartPhone, HouseType, OwnHouse, NbRoomsHouse, YearsInHouse, Income, Gender, BirthYear, Mothertongue, FamilSitu, OccupStat, SocioProfCat, CalculatedIncome, Education, HalfFareST, LineRelST, GenAbST, AreaRelST, OtherST, CarAvail, MarginalCostPT, CostCarCHF, Envir01, Envir02, Envir03, Envir04, Envir05, Envir06, Mobil01, Mobil02, Mobil03, Mobil04, Mobil05, Mobil06, Mobil07, Mobil08, Mobil09, Mobil10, Mobil11, Mobil12, Mobil13, Mobil14, Mobil15, Mobil16, Mobil17, Mobil18, Mobil19, Mobil20, Mobil21, Mobil22, Mobil23, Mobil24, Mobil25, Mobil26, Mobil27, ResidCh01, ResidCh02, ResidCh03, ResidCh04, ResidCh05, ResidCh06, ResidCh07, LifSty01, LifSty02, LifSty03, LifSty04, LifSty05, LifSty06, LifSty07, LifSty08, LifSty09, LifSty10, LifSty11, LifSty12, LifSty13, LifSty14, TripPurpose, TypeCommune, UrbRur, LangCode, ...]
Index: []

[0 rows x 117 columns]

In [ ]:
#Cleaning House types
#Cleaning HouseType variable
df_mod[df_mod['HouseType']<0]
df_mod.drop(df_mod[df_mod['HouseType']<0].index,inplace=True)
df_mod[df_mod['HouseType']<0]

#Cleaning OwnHouse variable
df_mod[df_mod['OwnHouse']<0]
df_mod.drop(df_mod[df_mod['OwnHouse']<0].index,inplace=True)
df_mod[df_mod['OwnHouse']<0]

#Cleaning NbRoomsHouse variable
df_mod[df_mod['NbRoomsHouse']<0]
df_mod.drop(df_mod[df_mod['NbRoomsHouse']<0].index,inplace=True)
df_mod[df_mod['NbRoomsHouse']<0]

#Cleaning YearsInHouse variable
df_mod[df_mod['YearsInHouse']<0]
df_mod.drop(df_mod[df_mod['YearsInHouse']<0].index,inplace=True)
df_mod[df_mod['YearsInHouse']<0]

df_mod.count()

Empty DataFrame
Columns: [ID, DestAct, NbTransf, TimePT, WalkingTimePT, WaitingTimePT, CostPT, CostCar, TimeCar, NbHousehold, NbChild, NbCar, NbMoto, NbBicy, NbBicyChild, NbComp, NbTV, Internet, NewsPaperSubs, NbCellPhones, NbSmartPhone, HouseType, OwnHouse, NbRoomsHouse, YearsInHouse, Income, Gender, BirthYear, Mothertongue, FamilSitu, OccupStat, SocioProfCat, CalculatedIncome, Education, HalfFareST, LineRelST, GenAbST, AreaRelST, OtherST, CarAvail, MarginalCostPT, CostCarCHF, Envir01, Envir02, Envir03, Envir04, Envir05, Envir06, Mobil01, Mobil02, Mobil03, Mobil04, Mobil05, Mobil06, Mobil07, Mobil08, Mobil09, Mobil10, Mobil11, Mobil12, Mobil13, Mobil14, Mobil15, Mobil16, Mobil17, Mobil18, Mobil19, Mobil20, Mobil21, Mobil22, Mobil23, Mobil24, Mobil25, Mobil26, Mobil27, ResidCh01, ResidCh02, ResidCh03, ResidCh04, ResidCh05, ResidCh06, ResidCh07, LifSty01, LifSty02, LifSty03, LifSty04, LifSty05, LifSty06, LifSty07, LifSty08, LifSty09, LifSty10, LifSty11, LifSty12, LifSty13, LifSty14, TripPurpose, TypeCommune, UrbRur, LangCode, ...]
Index: []

[0 rows x 117 columns]

In [117]:
#Socio-income variables

#Cleaning Income variable
df_mod[df_mod['Income']<0]
df_mod.drop(df_mod[df_mod['Income']<0].index,inplace=True)  
df_mod[df_mod['Income']<0]

#Cleaning the Gender variable
df_mod[df_mod['Gender']<0]
df_mod.drop(df_mod[df_mod['Gender']<0].index,inplace=True)
df_mod[df_mod['Gender']<0]

#Cleaning the BirthYear variable
df_mod[df_mod['BirthYear']<0]
df_mod.drop(df_mod[df_mod['BirthYear']<0].index,inplace=True)
df_mod[df_mod['BirthYear']<0]

#Cleaning the Mothertongue variable
df_mod[df_mod['Mothertongue']<0]    
df_mod.drop(df_mod[df_mod['Mothertongue']<0].index,inplace=True)
df_mod[df_mod['Mothertongue']<0]

#Cleaning the FamilSitu
df_mod[df_mod['FamilSitu']<0]
df_mod.drop(df_mod[df_mod['FamilSitu']<0].index,inplace=True)
df_mod[df_mod['FamilSitu']<0]

#Cleaning OccupStat
df_mod[df_mod['OccupStat']<0]
df_mod.drop(df_mod[df_mod['OccupStat']<0].index,inplace=True)
df_mod[df_mod['OccupStat']<0]

#Cleaning SocioProfCat  
df_mod[df_mod['SocioProfCat']<0]
df_mod.drop(df_mod[df_mod['SocioProfCat']<0].index,inplace=True)
df_mod[df_mod['SocioProfCat']<0]

Empty DataFrame
Columns: [ID, DestAct, NbTransf, TimePT, WalkingTimePT, WaitingTimePT, CostPT, CostCar, TimeCar, NbHousehold, NbChild, NbCar, NbMoto, NbBicy, NbBicyChild, NbComp, NbTV, Internet, NewsPaperSubs, NbCellPhones, NbSmartPhone, HouseType, OwnHouse, NbRoomsHouse, YearsInHouse, Income, Gender, BirthYear, Mothertongue, FamilSitu, OccupStat, SocioProfCat, CalculatedIncome, Education, HalfFareST, LineRelST, GenAbST, AreaRelST, OtherST, CarAvail, MarginalCostPT, CostCarCHF, Envir01, Envir02, Envir03, Envir04, Envir05, Envir06, Mobil01, Mobil02, Mobil03, Mobil04, Mobil05, Mobil06, Mobil07, Mobil08, Mobil09, Mobil10, Mobil11, Mobil12, Mobil13, Mobil14, Mobil15, Mobil16, Mobil17, Mobil18, Mobil19, Mobil20, Mobil21, Mobil22, Mobil23, Mobil24, Mobil25, Mobil26, Mobil27, ResidCh01, ResidCh02, ResidCh03, ResidCh04, ResidCh05, ResidCh06, ResidCh07, LifSty01, LifSty02, LifSty03, LifSty04, LifSty05, LifSty06, LifSty07, LifSty08, LifSty09, LifSty10, LifSty11, LifSty12, LifSty13, LifSty14, TripPurpose, TypeCommune, UrbRur, LangCode, ...]
Index: []

[0 rows x 117 columns]

In [ ]:
df_mod.count()
df_mod

ID                  920
DestAct             920
NbTransf            920
TimePT              920
WalkingTimePT       920
                   ...
ModeToSchool        920
ReportedDuration    920
CoderegionCAR       920
age                 920
Weight              920
Length: 117, dtype: int64

In [119]:
#SeasonTicket variable
#Cleaning the HalfFareST Variable
df_mod[df_mod['HalfFareST']<0]
df_mod.drop(df_mod[df_mod['HalfFareST']<0].index,inplace=True)
df_mod[df_mod['HalfFareST']<0]

#Cleaning the LineRelST
df_mod[df_mod['LineRelST']<0]
df_mod.drop(df_mod[df_mod['LineRelST']<0].index,inplace=True)
df_mod[df_mod['LineRelST']<0]

#Cleaning the GenAbST variable
df_mod[df_mod['GenAbST']<0]
df_mod.drop(df_mod[df_mod['GenAbST']<0].index,inplace=True)
df_mod[df_mod['GenAbST']<0]

#Cleaning the AreaRelST variable
df_mod[df_mod['AreaRelST']<0]
df_mod.drop(df_mod[df_mod['AreaRelST']<0].index,inplace=True)
df_mod[df_mod['AreaRelST']<0]

#Cleaning the OtherST variable
df_mod[df_mod['OtherST']<0]
df_mod.drop(df_mod[df_mod['OtherST']<0].index,inplace=True)
df_mod[df_mod['OtherST']<0]

Empty DataFrame
Columns: [ID, DestAct, NbTransf, TimePT, WalkingTimePT, WaitingTimePT, CostPT, CostCar, TimeCar, NbHousehold, NbChild, NbCar, NbMoto, NbBicy, NbBicyChild, NbComp, NbTV, Internet, NewsPaperSubs, NbCellPhones, NbSmartPhone, HouseType, OwnHouse, NbRoomsHouse, YearsInHouse, Income, Gender, BirthYear, Mothertongue, FamilSitu, OccupStat, SocioProfCat, CalculatedIncome, Education, HalfFareST, LineRelST, GenAbST, AreaRelST, OtherST, CarAvail, MarginalCostPT, CostCarCHF, Envir01, Envir02, Envir03, Envir04, Envir05, Envir06, Mobil01, Mobil02, Mobil03, Mobil04, Mobil05, Mobil06, Mobil07, Mobil08, Mobil09, Mobil10, Mobil11, Mobil12, Mobil13, Mobil14, Mobil15, Mobil16, Mobil17, Mobil18, Mobil19, Mobil20, Mobil21, Mobil22, Mobil23, Mobil24, Mobil25, Mobil26, Mobil27, ResidCh01, ResidCh02, ResidCh03, ResidCh04, ResidCh05, ResidCh06, ResidCh07, LifSty01, LifSty02, LifSty03, LifSty04, LifSty05, LifSty06, LifSty07, LifSty08, LifSty09, LifSty10, LifSty11, LifSty12, LifSty13, LifSty14, TripPurpose, TypeCommune, UrbRur, LangCode, ...]
Index: []

[0 rows x 117 columns]

In [121]:
#Cleaning the Education variable
df_mod[df_mod['Education']<0]
df_mod.drop(df_mod[df_mod['Education']<0].index,inplace=True)
df_mod[df_mod['Education']<0]

Empty DataFrame
Columns: [ID, DestAct, NbTransf, TimePT, WalkingTimePT, WaitingTimePT, CostPT, CostCar, TimeCar, NbHousehold, NbChild, NbCar, NbMoto, NbBicy, NbBicyChild, NbComp, NbTV, Internet, NewsPaperSubs, NbCellPhones, NbSmartPhone, HouseType, OwnHouse, NbRoomsHouse, YearsInHouse, Income, Gender, BirthYear, Mothertongue, FamilSitu, OccupStat, SocioProfCat, CalculatedIncome, Education, HalfFareST, LineRelST, GenAbST, AreaRelST, OtherST, CarAvail, MarginalCostPT, CostCarCHF, Envir01, Envir02, Envir03, Envir04, Envir05, Envir06, Mobil01, Mobil02, Mobil03, Mobil04, Mobil05, Mobil06, Mobil07, Mobil08, Mobil09, Mobil10, Mobil11, Mobil12, Mobil13, Mobil14, Mobil15, Mobil16, Mobil17, Mobil18, Mobil19, Mobil20, Mobil21, Mobil22, Mobil23, Mobil24, Mobil25, Mobil26, Mobil27, ResidCh01, ResidCh02, ResidCh03, ResidCh04, ResidCh05, ResidCh06, ResidCh07, LifSty01, LifSty02, LifSty03, LifSty04, LifSty05, LifSty06, LifSty07, LifSty08, LifSty09, LifSty10, LifSty11, LifSty12, LifSty13, LifSty14, TripPurpose, TypeCommune, UrbRur, LangCode, ...]
Index: []

[0 rows x 117 columns]

In [122]:
df_mod.count()

ID                  919
DestAct             919
NbTransf            919
TimePT              919
WalkingTimePT       919
                   ...
ModeToSchool        919
ReportedDuration    919
CoderegionCAR       919
age                 919
Weight              919
Length: 117, dtype: int64

In [124]:
#Cleaning the Residential Attitudes

#Cleaning the ResidCh01 variable
df_mod[df_mod['ResidCh01']<0]
df_mod.drop(df_mod[df_mod['ResidCh01']<0].index,inplace=True)

#Cleaning the ResidCh02 variable
df_mod[df_mod['ResidCh02']<0]
df_mod.drop(df_mod[df_mod['ResidCh02']<0].index,inplace=True)
df_mod[df_mod['ResidCh02']<0]

#Cleaning the ResidCh03 variable
df_mod[df_mod['ResidCh03']<0]
df_mod.drop(df_mod[df_mod['ResidCh03']<0].index,inplace=True)
df_mod[df_mod['ResidCh03']<0]

#Cleaning the ResidCh04 variable
df_mod[df_mod['ResidCh04']<0]
df_mod.drop(df_mod[df_mod['ResidCh04']<0].index,inplace=True)
df_mod[df_mod['ResidCh04']<0]

#Cleaning the ResidCh05 variable
df_mod[df_mod['ResidCh05']<0]
df_mod.drop(df_mod[df_mod['ResidCh05']<0].index,inplace=True)
df_mod[df_mod['ResidCh05']<0]

#Cleaning the ResidCh06 variable
df_mod[df_mod['ResidCh06']<0]
df_mod.drop(df_mod[df_mod['ResidCh06']<0].index,inplace=True)
df_mod[df_mod['ResidCh06']<0]

#Cleaning the ResidCh07 variable
df_mod[df_mod['ResidCh07']<0]
df_mod.drop(df_mod[df_mod['ResidCh07']<0].index,inplace=True)
df_mod[df_mod['ResidCh07']<0]

Empty DataFrame
Columns: [ID, DestAct, NbTransf, TimePT, WalkingTimePT, WaitingTimePT, CostPT, CostCar, TimeCar, NbHousehold, NbChild, NbCar, NbMoto, NbBicy, NbBicyChild, NbComp, NbTV, Internet, NewsPaperSubs, NbCellPhones, NbSmartPhone, HouseType, OwnHouse, NbRoomsHouse, YearsInHouse, Income, Gender, BirthYear, Mothertongue, FamilSitu, OccupStat, SocioProfCat, CalculatedIncome, Education, HalfFareST, LineRelST, GenAbST, AreaRelST, OtherST, CarAvail, MarginalCostPT, CostCarCHF, Envir01, Envir02, Envir03, Envir04, Envir05, Envir06, Mobil01, Mobil02, Mobil03, Mobil04, Mobil05, Mobil06, Mobil07, Mobil08, Mobil09, Mobil10, Mobil11, Mobil12, Mobil13, Mobil14, Mobil15, Mobil16, Mobil17, Mobil18, Mobil19, Mobil20, Mobil21, Mobil22, Mobil23, Mobil24, Mobil25, Mobil26, Mobil27, ResidCh01, ResidCh02, ResidCh03, ResidCh04, ResidCh05, ResidCh06, ResidCh07, LifSty01, LifSty02, LifSty03, LifSty04, LifSty05, LifSty06, LifSty07, LifSty08, LifSty09, LifSty10, LifSty11, LifSty12, LifSty13, LifSty14, TripPurpose, TypeCommune, UrbRur, LangCode, ...]
Index: []

[0 rows x 117 columns]

In [125]:
df_mod.count()

ID                  911
DestAct             911
NbTransf            911
TimePT              911
WalkingTimePT       911
                   ...
ModeToSchool        911
ReportedDuration    911
CoderegionCAR       911
age                 911
Weight              911
Length: 117, dtype: int64

In [127]:
#Cleaning the LifeStyle Attitudes

df_mod[df_mod['LifSty01']<0]
df_mod.drop(df_mod[df_mod['LifSty01']<0].index,inplace=True)
df_mod[df_mod['LifSty01']<0]

df_mod[df_mod['LifSty02']<0]
df_mod.drop(df_mod[df_mod['LifSty02']<0].index,inplace=True)
df_mod[df_mod['LifSty02']<0]

df_mod[df_mod['LifSty03']<0]
df_mod.drop(df_mod[df_mod['LifSty03']<0].index,inplace=True)
df_mod[df_mod['LifSty03']<0]

df_mod[df_mod['LifSty04']<0]
df_mod.drop(df_mod[df_mod['LifSty04']<0].index,inplace=True)
df_mod[df_mod['LifSty04']<0]

df_mod[df_mod['LifSty05']<0]
df_mod.drop(df_mod[df_mod['LifSty05']<0].index,inplace=True)
df_mod[df_mod['LifSty05']<0]

df_mod[df_mod['LifSty06']<0]
df_mod.drop(df_mod[df_mod['LifSty06']<0].index,inplace=True)
df_mod[df_mod['LifSty06']<0]

df_mod[df_mod['LifSty07']<0]
df_mod.drop(df_mod[df_mod['LifSty07']<0].index,inplace=True)
df_mod[df_mod['LifSty07']<0]

df_mod[df_mod['LifSty08']<0]
df_mod.drop(df_mod[df_mod['LifSty08']<0].index,inplace=True)
df_mod[df_mod['LifSty08']<0]

df_mod[df_mod['LifSty09']<0]
df_mod.drop(df_mod[df_mod['LifSty09']<0].index,inplace=True)
df_mod[df_mod['LifSty09']<0]   

df_mod[df_mod['LifSty10']<0]
df_mod.drop(df_mod[df_mod['LifSty10']<0].index,inplace=True)
df_mod[df_mod['LifSty10']<0]

df_mod[df_mod['LifSty11']<0]
df_mod.drop(df_mod[df_mod['LifSty11']<0].index,inplace=True)
df_mod[df_mod['LifSty11']<0]

df_mod[df_mod['LifSty12']<0]
df_mod.drop(df_mod[df_mod['LifSty12']<0].index,inplace=True)   
df_mod[df_mod['LifSty12']<0]

df_mod[df_mod['LifSty13']<0]
df_mod.drop(df_mod[df_mod['LifSty13']<0].index,inplace=True)
df_mod[df_mod['LifSty13']<0]

df_mod[df_mod['LifSty14']<0]
df_mod.drop(df_mod[df_mod['LifSty14']<0].index,inplace=True)
df_mod[df_mod['LifSty14']<0]

df_mod.count()

ID                  900
DestAct             900
NbTransf            900
TimePT              900
WalkingTimePT       900
                   ...
ModeToSchool        900
ReportedDuration    900
CoderegionCAR       900
age                 900
Weight              900
Length: 117, dtype: int64

In [128]:
# df2=df.copy()

# cols=list(df2.columns.values)

In [129]:
# list(df_mod.columns.values)

In [130]:
df_mod.to_csv('Cleaned_Data.csv',index=False)